/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.DeliveryPackage;
import Model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author 91730
 */
public class Create extends javax.swing.JPanel {

    /**
     * Creates new form Create
     */
    
    
    private DeliveryPackage delPackage;
    
    private boolean validate = false;
    
    public Create() {
        initComponents();
    }

    Create(DeliveryPackage deliveryPackage) {
        initComponents();
        
        this.delPackage = deliveryPackage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        packageId = new javax.swing.JLabel();
        packageWeight = new javax.swing.JLabel();
        productId = new javax.swing.JLabel();
        productName = new javax.swing.JLabel();
        productPrice = new javax.swing.JLabel();
        packageIdText = new javax.swing.JTextField();
        packageWeightText = new javax.swing.JTextField();
        productIdText = new javax.swing.JTextField();
        productNameText = new javax.swing.JTextField();
        productPriceText = new javax.swing.JTextField();
        customerName = new javax.swing.JLabel();
        customerId = new javax.swing.JLabel();
        customerNameText = new javax.swing.JTextField();
        customerIdText = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        saveProduct = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        packageId.setText("Package Id");
        add(packageId, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 41, -1, -1));

        packageWeight.setText("Weight");
        add(packageWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 86, -1, -1));

        productId.setText("Product Id");
        add(productId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        productName.setText("Product Name");
        add(productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        productPrice.setText("Product Price");
        add(productPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        packageIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageIdTextActionPerformed(evt);
            }
        });
        add(packageIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 38, 55, -1));

        packageWeightText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageWeightTextActionPerformed(evt);
            }
        });
        add(packageWeightText, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 83, 55, -1));

        productIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productIdTextActionPerformed(evt);
            }
        });
        add(productIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 55, -1));
        add(productNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 55, -1));

        productPriceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productPriceTextActionPerformed(evt);
            }
        });
        add(productPriceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 55, -1));

        customerName.setText("Customer Name");
        add(customerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 41, -1, -1));

        customerId.setText("Customer Id");
        add(customerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 96, -1, -1));

        customerNameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                customerNameTextFocusLost(evt);
            }
        });
        add(customerNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 38, 53, -1));
        add(customerIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 93, 53, -1));

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        saveProduct.setText("Save Product");
        saveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProductActionPerformed(evt);
            }
        });
        add(saveProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void packageWeightTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageWeightTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packageWeightTextActionPerformed

    private void productPriceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productPriceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productPriceTextActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        
        String id = packageIdText.getText();
        String weight = packageWeightText.getText();
        
        String customerId = customerIdText.getText();
        String customerName = customerNameText.getText();
        
        this.delPackage.setPackageId((Integer.valueOf(id)));
        this.delPackage.setPackageWeight(Double.valueOf(weight));
        
       Customer customer = this.delPackage.getCustomer();
       customer.setCustomerId(Integer.valueOf(customerId));
       customer.setFullName(customerName);
       
       
       if(validate){
           JOptionPane.showMessageDialog(null, "Enter details in all fields");
       } else{
           JOptionPane.showMessageDialog(null, "Details Saved Successfully!");
       }
       
       
       
       
    }//GEN-LAST:event_saveActionPerformed

    private void saveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProductActionPerformed
        // TODO add your handling code here:
        
        String productId = productIdText.getText();
        String productName = productNameText.getText();
        String productPrice = productPriceText.getText();
        
        Product product = this.delPackage.createProduct(Integer.valueOf(productId),productName,Double.valueOf(productPrice));
        
        JOptionPane.showMessageDialog(null, "Product successfully added!");    
    }//GEN-LAST:event_saveProductActionPerformed

    
    private void productIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productIdTextActionPerformed

    private void customerNameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerNameTextFocusLost
        // TODO add your handling code here:
        System.out.println(customerNameText.getText() + " -- the customer name");
        String name = customerNameText.getText();
        
        if(name.isEmpty()) {
           // JOptionPane.showMessageDialog(null, "Please fill name");
            this.validate = true;
        } else {
            this.validate = false;
        }
    }//GEN-LAST:event_customerNameTextFocusLost

    private void packageIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packageIdTextActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel customerId;
    private javax.swing.JTextField customerIdText;
    private javax.swing.JLabel customerName;
    private javax.swing.JTextField customerNameText;
    private javax.swing.JLabel packageId;
    private javax.swing.JTextField packageIdText;
    private javax.swing.JLabel packageWeight;
    private javax.swing.JTextField packageWeightText;
    private javax.swing.JLabel productId;
    private javax.swing.JTextField productIdText;
    private javax.swing.JLabel productName;
    private javax.swing.JTextField productNameText;
    private javax.swing.JLabel productPrice;
    private javax.swing.JTextField productPriceText;
    private javax.swing.JButton save;
    private javax.swing.JButton saveProduct;
    // End of variables declaration//GEN-END:variables
}
