/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.DeliveryPackage;

/**
 *
 * @author 91730
 */
public class Display extends javax.swing.JPanel {

    private DeliveryPackage delPackage;
    /**
     * Creates new form Display
     */
    public Display() {
        initComponents();
    }
    
    public Display(DeliveryPackage deliveryPackage) {
        initComponents();
        
        this.delPackage = deliveryPackage;
        display();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        packageId = new javax.swing.JLabel();
        packageWeight = new javax.swing.JLabel();
        packageIdText = new javax.swing.JTextField();
        packageWeightText = new javax.swing.JTextField();
        customerName = new javax.swing.JLabel();
        customerId = new javax.swing.JLabel();
        customerNameText = new javax.swing.JTextField();
        customerIdText = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        packageId.setText("Package Id");
        add(packageId, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 41, -1, -1));

        packageWeight.setText("Weight");
        add(packageWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 86, -1, -1));
        add(packageIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 38, 55, -1));

        packageWeightText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageWeightTextActionPerformed(evt);
            }
        });
        add(packageWeightText, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 83, 55, -1));

        customerName.setText("Customer Name");
        add(customerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 41, -1, -1));

        customerId.setText("Customer Id");
        add(customerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 96, -1, -1));
        add(customerNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 38, 53, -1));
        add(customerIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 93, 53, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void packageWeightTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageWeightTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packageWeightTextActionPerformed

    public void display(){
        packageIdText.setText(String.valueOf(this.delPackage.getPackageId()));
        packageWeightText.setText(String.valueOf(this.delPackage.getPackageWeight()));
        
        Customer cust = this.delPackage.getCustomer();
        customerIdText.setText(String.valueOf(cust.getCustomerId()));
        customerNameText.setText(cust.getFullName());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customerId;
    private javax.swing.JTextField customerIdText;
    private javax.swing.JLabel customerName;
    private javax.swing.JTextField customerNameText;
    private javax.swing.JLabel packageId;
    private javax.swing.JTextField packageIdText;
    private javax.swing.JLabel packageWeight;
    private javax.swing.JTextField packageWeightText;
    // End of variables declaration//GEN-END:variables
}
