/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.DeliveryPackage;
import Model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author 91730
 */
public class Update extends javax.swing.JPanel {

    /**
     * Creates new form Update
     */
    
    private DeliveryPackage delPackage;
    private Product productViewed;
    public Update() {
        initComponents();
    }

    public Update(DeliveryPackage deliveryPackage) {
        initComponents();
        this.delPackage  = deliveryPackage;
        displayPackageDetails();
        displayProductList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        packageWeightText = new javax.swing.JTextField();
        productIdText = new javax.swing.JTextField();
        productNameText = new javax.swing.JTextField();
        productPriceText = new javax.swing.JTextField();
        packageId = new javax.swing.JLabel();
        customerName = new javax.swing.JLabel();
        packageWeight = new javax.swing.JLabel();
        customerId = new javax.swing.JLabel();
        productId = new javax.swing.JLabel();
        customerNameText = new javax.swing.JTextField();
        customerIdText = new javax.swing.JTextField();
        productName = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        productPrice = new javax.swing.JLabel();
        packageIdText = new javax.swing.JTextField();
        updateProduct = new javax.swing.JButton();
        showBtn = new javax.swing.JButton();
        productComboBox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(51, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        packageWeightText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageWeightTextActionPerformed(evt);
            }
        });
        add(packageWeightText, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 83, 55, -1));
        add(productIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 231, 55, -1));

        productNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameTextActionPerformed(evt);
            }
        });
        add(productNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 279, 55, -1));

        productPriceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productPriceTextActionPerformed(evt);
            }
        });
        add(productPriceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 323, 55, -1));

        packageId.setText("Package Id");
        add(packageId, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 41, -1, -1));

        customerName.setText("Customer Name");
        add(customerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 38, -1, -1));

        packageWeight.setText("Weight");
        add(packageWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 86, -1, -1));

        customerId.setText("Customer Id");
        add(customerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 87, -1, -1));

        productId.setText("Product Id");
        add(productId, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 234, -1, -1));
        add(customerNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 38, 53, -1));
        add(customerIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 93, 53, -1));

        productName.setText("Product Name");
        add(productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 282, -1, -1));

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 151, -1, -1));

        productPrice.setText("Product Price");
        add(productPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 326, -1, -1));
        add(packageIdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 38, 55, -1));

        updateProduct.setText("Update Product");
        updateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProductActionPerformed(evt);
            }
        });
        add(updateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 294, -1, -1));

        showBtn.setText("Show");
        showBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBtnActionPerformed(evt);
            }
        });
        add(showBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 164, -1, -1));

        productComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productComboBoxActionPerformed(evt);
            }
        });
        add(productComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 165, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void packageWeightTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageWeightTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packageWeightTextActionPerformed

    private void productPriceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productPriceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productPriceTextActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:

        String id = packageIdText.getText();
        String weight = packageWeightText.getText();
//        String productId = productIdText.getText();
//        String productName = productNameText.getText();
//        String productPrice = productPriceText.getText();
        String customerId = customerIdText.getText();
        String customerName = customerNameText.getText();

        this.delPackage.setPackageId((Integer.valueOf(id)));
        this.delPackage.setPackageWeight(Double.valueOf(weight));

//        Product product = this.delPackage.getProduct();
//        product.setProductId(Integer.valueOf(productId));
//        product.setProductName(productName);
//        product.setPrice(Integer.valueOf(productPrice));

        Customer customer = this.delPackage.getCustomer();
        customer.setCustomerId(Integer.valueOf(customerId));
        customer.setFullName(customerName);

    }//GEN-LAST:event_updateBtnActionPerformed

    private void updateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProductActionPerformed
        // TODO add your handling code here:
        this.productViewed.setProductName(productNameText.getText());
        this.productViewed.setPrice(Double.valueOf(productPriceText.getText()));
    }//GEN-LAST:event_updateProductActionPerformed

    private void showBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBtnActionPerformed
        // TODO add your handling code here:
        productIdText.setEnabled(false);
        int pid = (int)productComboBox.getSelectedItem();
        
        Product prod = this.delPackage.findProduct(pid);
        this.productViewed = prod;
        
        if(!prod.equals(null)){
            System.out.println(String.valueOf(pid));
             System.out.println(prod.getProductName());
            productIdText.setText(String.valueOf(pid));
            productNameText.setText(prod.getProductName());
            productPriceText.setText(String.valueOf(prod.getPrice()));
        } else{
            JOptionPane.showMessageDialog(null, "Product can't be located");
        }
        
        
    }//GEN-LAST:event_showBtnActionPerformed

    private void productComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productComboBoxActionPerformed

    private void productNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameTextActionPerformed


     public void displayProductList() {
        
         for(Product p: this.delPackage.getProductList()){
             productComboBox.addItem(p.getProductId());
         }
        
    }
     
     public void displayPackageDetails() {
        packageIdText.setText(String.valueOf(this.delPackage.getPackageId()));
        packageWeightText.setText(String.valueOf(this.delPackage.getPackageWeight()));
        
        Customer cust = this.delPackage.getCustomer();
        customerIdText.setText(String.valueOf(cust.getCustomerId()));
        customerNameText.setText(cust.getFullName());
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customerId;
    private javax.swing.JTextField customerIdText;
    private javax.swing.JLabel customerName;
    private javax.swing.JTextField customerNameText;
    private javax.swing.JLabel packageId;
    private javax.swing.JTextField packageIdText;
    private javax.swing.JLabel packageWeight;
    private javax.swing.JTextField packageWeightText;
    private javax.swing.JComboBox productComboBox;
    private javax.swing.JLabel productId;
    private javax.swing.JTextField productIdText;
    private javax.swing.JLabel productName;
    private javax.swing.JTextField productNameText;
    private javax.swing.JLabel productPrice;
    private javax.swing.JTextField productPriceText;
    private javax.swing.JButton showBtn;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton updateProduct;
    // End of variables declaration//GEN-END:variables
}
